/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.smalluml.SmallUML.ui.internal.SmallUMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmallUMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmallUMLActivator.getInstance().getInjector(SmallUMLActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL);
	}
	
}
