/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.smalluml.services.SmallUMLGrammarAccess;
import smalluml.Association;
import smalluml.Attribut;
import smalluml.Booleen;
import smalluml.Cardinalite;
import smalluml.Chaine;
import smalluml.Classe;
import smalluml.Element;
import smalluml.Entier;
import smalluml.Enumeration;
import smalluml.Methode;
import smalluml.SmallumlPackage;
import smalluml.TypeDonnee;

@SuppressWarnings("all")
public class SmallUMLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SmallUMLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SmallumlPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SmallumlPackage.ASSOCIATION:
				sequence_Association(context, (Association) semanticObject); 
				return; 
			case SmallumlPackage.ATTRIBUT:
				sequence_Attribut(context, (Attribut) semanticObject); 
				return; 
			case SmallumlPackage.BOOLEEN:
				sequence_Booleen(context, (Booleen) semanticObject); 
				return; 
			case SmallumlPackage.CARDINALITE:
				sequence_Cardinalite(context, (Cardinalite) semanticObject); 
				return; 
			case SmallumlPackage.CHAINE:
				sequence_Chaine(context, (Chaine) semanticObject); 
				return; 
			case SmallumlPackage.CLASSE:
				sequence_Classe(context, (Classe) semanticObject); 
				return; 
			case SmallumlPackage.ELEMENT:
				sequence_Element(context, (Element) semanticObject); 
				return; 
			case SmallumlPackage.ENTIER:
				sequence_Entier(context, (Entier) semanticObject); 
				return; 
			case SmallumlPackage.ENUMERATION:
				sequence_Enumeration(context, (Enumeration) semanticObject); 
				return; 
			case SmallumlPackage.METHODE:
				sequence_Methode(context, (Methode) semanticObject); 
				return; 
			case SmallumlPackage.TYPE_DONNEE:
				sequence_TypeDonnee(context, (TypeDonnee) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Association returns Association
	 *
	 * Constraint:
	 *     (nomAssociation=EString cardinalites+=Cardinalite cardinalites+=Cardinalite+)
	 */
	protected void sequence_Association(ISerializationContext context, Association semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Attribut returns Attribut
	 *
	 * Constraint:
	 *     (nomAttribut=EString type=[Type|ID])
	 */
	protected void sequence_Attribut(ISerializationContext context, Attribut semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmallumlPackage.Literals.ATTRIBUT__NOM_ATTRIBUT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmallumlPackage.Literals.ATTRIBUT__NOM_ATTRIBUT));
			if (transientValues.isValueTransient(semanticObject, SmallumlPackage.Literals.ATTRIBUT__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmallumlPackage.Literals.ATTRIBUT__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAttributAccess().getNomAttributEStringParserRuleCall_2_0(), semanticObject.getNomAttribut());
		feeder.accept(grammarAccess.getAttributAccess().getTypeTypeIDTerminalRuleCall_3_0_1(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Type returns Booleen
	 *     Booleen returns Booleen
	 *
	 * Constraint:
	 *     nomType='Booleen'
	 */
	protected void sequence_Booleen(ISerializationContext context, Booleen semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmallumlPackage.Literals.TYPE__NOM_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmallumlPackage.Literals.TYPE__NOM_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBooleenAccess().getNomTypeBooleenKeyword_0(), semanticObject.getNomType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Cardinalite returns Cardinalite
	 *
	 * Constraint:
	 *     multiplicite=EString
	 */
	protected void sequence_Cardinalite(ISerializationContext context, Cardinalite semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmallumlPackage.Literals.CARDINALITE__MULTIPLICITE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmallumlPackage.Literals.CARDINALITE__MULTIPLICITE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCardinaliteAccess().getMultipliciteEStringParserRuleCall_1_0(), semanticObject.getMultiplicite());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Type returns Chaine
	 *     Chaine returns Chaine
	 *
	 * Constraint:
	 *     nomType='Chaine'
	 */
	protected void sequence_Chaine(ISerializationContext context, Chaine semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmallumlPackage.Literals.TYPE__NOM_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmallumlPackage.Literals.TYPE__NOM_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getChaineAccess().getNomTypeChaineKeyword_0(), semanticObject.getNomType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Classe returns Classe
	 *
	 * Constraint:
	 *     (
	 *         nomClasse=EString 
	 *         attributs+=Attribut* 
	 *         methodes+=Methode* 
	 *         cardinalites+=Cardinalite* 
	 *         sousClasses+=Classe* 
	 *         superClasse=[Classe|ID]
	 *     )
	 */
	protected void sequence_Classe(ISerializationContext context, Classe semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Element
	 *
	 * Constraint:
	 *     nomElement=EString
	 */
	protected void sequence_Element(ISerializationContext context, Element semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmallumlPackage.Literals.ELEMENT__NOM_ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmallumlPackage.Literals.ELEMENT__NOM_ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getElementAccess().getNomElementEStringParserRuleCall_0(), semanticObject.getNomElement());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Type returns Entier
	 *     Entier returns Entier
	 *
	 * Constraint:
	 *     nomType='Entier'
	 */
	protected void sequence_Entier(ISerializationContext context, Entier semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmallumlPackage.Literals.TYPE__NOM_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmallumlPackage.Literals.TYPE__NOM_TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEntierAccess().getNomTypeEntierKeyword_0(), semanticObject.getNomType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Type returns Enumeration
	 *     Enumeration returns Enumeration
	 *
	 * Constraint:
	 *     (nomEnumeration=EString elements+=Element*)
	 */
	protected void sequence_Enumeration(ISerializationContext context, Enumeration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Methode returns Methode
	 *
	 * Constraint:
	 *     (typeDeRetour=[Type|ID] nomMethode=EString parametres+=Attribut*)
	 */
	protected void sequence_Methode(ISerializationContext context, Methode semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns TypeDonnee
	 *     TypeDonnee returns TypeDonnee
	 *
	 * Constraint:
	 *     (nomType=EString attributs+=Attribut*)
	 */
	protected void sequence_TypeDonnee(ISerializationContext context, TypeDonnee semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
