<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smalluml" nsURI="http://www.univ-nantes.fr/smalluml" nsPrefix="smalluml">
  <eClassifiers xsi:type="ecore:EClass" name="Classe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomClasse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributs" upperBound="-1"
        eType="#//Attribut" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodes" upperBound="-1"
        eType="#//Methode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstrait" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinalites" upperBound="-1"
        eType="#//Cardinalite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sousClasses" upperBound="-1"
        eType="#//Classe" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClasse" eType="#//Classe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomAttribut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomEnumeration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Methode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomMethode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDeRetour" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametres" upperBound="-1"
        eType="#//Attribut" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstrait" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDonnee" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributs" upperBound="-1"
        eType="#//Attribut" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomAssociation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinalites" lowerBound="2"
        upperBound="-1" eType="#//Cardinalite" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cardinalite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chaine" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entier" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Booleen" eSuperTypes="#//Type"/>
</ecore:EPackage>
