/*
 * generated by Xtext 2.10.0
 */
package org.smalluml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmallUMLStandaloneSetup extends SmallUMLStandaloneSetupGenerated {

	def static void doSetup() {
		new SmallUMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
