/**
 * generated by Xtext 2.10.0
 */
package org.smalluml;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallUMLStandaloneSetup /* implements SmallUMLStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type SmallUMLStandaloneSetup");
  }
}
